version: "3.9"
services:
  db:
    image: mysql:8.0.34
    container_name: db
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: P@ssw0rd@gss
      MYSQL_DATABASE: itechco3_db
      MYSQL_USER: itechco3
      MYSQL_PASSWORD: P@ssw0rd@gss
    volumes:
      - ./init-db:/docker-entrypoint-initdb.d
      - ./db-data:/var/lib/mysql
    ports:
      - '3306:3306'
    networks:
      - mynetwork
    restart: always
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      - PMA_HOST=db
    depends_on:
      - db
    networks:
      - mynetwork
  api:
    build: .
    environment:
      DB_HOST: db
      DB_USER: itechco3
      DB_PASSWORD: P@ssw0rd@gss
      DB_DATABASE: itechco3_db
    restart: always
    ports:
      - '5000:5000'
    depends_on:
      - db
    networks:
      - mynetwork
  web:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - mynetwork
networks:
  mynetwork:
    driver: bridge